include:
  - board: nice_nano_v2
    shield: corne_left nice_oled
  - board: nice_nano_v2
    shield: corne_right nice_oled
  # Add dongle display configuration
  - board: nice_nano_v2
    shield: dongle_display